# Generated by Django 3.1.1 on 2020-09-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='apellido',
        ),
        migrations.AddField(
            model_name='bodega',
            name='cantidad',
            field=models.IntegerField(default=3),
        ),
    ]
